function initializeEuropeanCountries() {
    countries.push(
        {name: "Turkey", climate: "Warm", continent: "Eurasia", geo: "City", mood: "Relax", tours: "Food"},
        {name: "Belgium", climate: "Cold", continent: "Eurasia", geo: "City", mood: "Relax", tours: "Museum"},
        {name: "Italy", climate: "Warm", continent: "Eurasia", geo: "City", mood: "Relax", tours: "Food"},
        {name: "Spain", climate: "Warm", continent: "Eurasia", geo: "City", mood: "Relax", tours: "Food"},
        {name: "Portugal", climate: "Warm", continent: "Eurasia", geo: "City", mood: "Relax", tours: "Food"},
        {name: "France", climate: "Warm", continent: "Eurasia", geo: "City", mood: "Relax", tours: "Museum"},
        {name: "The Netherlands", climate: "Cold", continent: "Eurasia", geo: "City", mood: "Relax", tours: "Museum"},
        {name: "United Kingdom", climate: "Cold", continent: "Eurasia", geo: "City", mood: "Relax", tours: "Food"},
        {name: "Ireland", climate: "Cold", continent: "Eurasia", geo: "Nature", mood: "Experience", tours: "Museum"},
        {name: "Germany", climate: "Cold", continent: "Eurasia", geo: "City", mood: "Relax", tours: "Museum"},
        {name: "Russia", climate: "Cold", continent: "Eurasia", geo: "City", mood: "Experience", tours: "Food"},
        {name: "Ukraine", climate: "Cold", continent: "Eurasia", geo: "City", mood: "Experience", tours: "Food"},
        {name: "Sweden", climate: "Cold", continent: "Eurasia", geo: "Nature", mood: "Experience", tours: "Museum"},
        {name: "Norway", climate: "Cold", continent: "Eurasia", geo: "Nature", mood: "Experience", tours: "Museum"},
        {name: "Finland", climate: "Cold", continent: "Eurasia", geo: "Nature", mood: "Experience", tours: "Museum"},
        {name: "Poland", climate: "Cold", continent: "Eurasia", geo: "City", mood: "Relax", tours: "Food"},
        {name: "Romania", climate: "Cold", continent: "Eurasia", geo: "Nature", mood: "Experience", tours: "Food"},
        {name: "Belarus", climate: "Cold", continent: "Eurasia", geo: "City", mood: "Experience", tours: "Food"},
        {name: "Greece", climate: "Warm", continent: "Eurasia", geo: "City", mood: "Relax", tours: "Food"},
        {name: "Bulgaria", climate: "Warm", continent: "Eurasia", geo: "City", mood: "Relax", tours: "Food"},
        {name: "Iceland", climate: "Cold", continent: "Eurasia", geo: "Nature", mood: "Experience", tours: "Museum"},
        {name: "Hungary", climate: "Warm", continent: "Eurasia", geo: "City", mood: "Relax", tours: "Food"},
        {name: "Austria", climate: "Cold", continent: "Eurasia", geo: "City", mood: "Relax", tours: "Museum"},
        {name: "Czech Republic", climate: "Cold", continent: "Eurasia", geo: "City", mood: "Relax", tours: "Museum"},
        {name: "Serbia", climate: "Warm", continent: "Eurasia", geo: "City", mood: "Relax", tours: "Food"},
        {name: "Lithuania", climate: "Cold", continent: "Eurasia", geo: "City", mood: "Relax", tours: "Museum"},
        {name: "Latvia", climate: "Cold", continent: "Eurasia", geo: "City", mood: "Relax", tours: "Museum"},
        {name: "Croatia", climate: "Warm", continent: "Eurasia", geo: "Nature", mood: "Relax", tours: "Food"},
        {name: "Bosnia And Herzegovina", climate: "Warm", continent: "Eurasia", geo: "City", mood: "Relax", tours: "Food"},
        {name: "Slovakia", climate: "Cold", continent: "Eurasia", geo: "City", mood: "Relax", tours: "Museum"},
        {name: "Denmark", climate: "Cold", continent: "Eurasia", geo: "Nature", mood: "Relax", tours: "Museum"},
        {name: "Switzerland", climate: "Cold", continent: "Eurasia", geo: "Nature", mood: "Relax", tours: "Food"},
        {name: "Moldova", climate: "Cold", continent: "Eurasia", geo: "City", mood: "Relax", tours: "Museum"},
        {name: "Albania", climate: "Warm", continent: "Eurasia", geo: "City", mood: "Relax", tours: "Food"},
        {name: "North Macedonia", climate: "Warm", continent: "Eurasia", geo: "City", mood: "Relax", tours: "Food"},
        {name: "Slovenia", climate: "Cold", continent: "Eurasia", geo: "City", mood: "Relax", tours: "Museum"},
        {name: "Montenegro", climate: "Warm", continent: "Eurasia", geo: "Nature", mood: "Relax", tours: "Food"},
        {name: "Kosovo", climate: "Warm", continent: "Eurasia", geo: "City", mood: "Relax", tours: "Food"},
        {name: "Luxembourg", climate: "Cold", continent: "Eurasia", geo: "City", mood: "Relax", tours: "Museum"},
        {name: "Andorra", climate: "Warm", continent: "Eurasia", geo: "City", mood: "Relax", tours: "Food"},
        {name: "Malta", climate: "Warm", continent: "Eurasia", geo: "City", mood: "Relax", tours: "Food"},
        {name: "Liechtenstein", climate: "Cold", continent: "Eurasia", geo: "City", mood: "Relax", tours: "Museum"},
        {name: "San Marino", climate: "Warm", continent: "Eurasia", geo: "City", mood: "Relax", tours: "Food"},
        {name: "Monaco", climate: "Warm", continent: "Eurasia", geo: "City", mood: "Relax", tours: "Food"},
        {name: "Vatican City", climate: "Warm", continent: "Eurasia", geo: "City", mood: "Relax", tours: "Museum"},
        {name: "Cyprus", climate: "Warm", continent: "Eurasia", geo: "Nature", mood: "Experience", tours: "Food"},
    );
}

function initializeAsianCountries() {
    countries.push(
        {name: "China", climate: "Warm", continent: "Eurasia", geo: "Nature", mood: "Experience", tours: "Food"},
        {name: "India", climate: "Warm", continent: "Eurasia", geo: "City", mood: "Experience", tours: "Food"},
        {name: "Kazakhstan", climate: "Cold", continent: "Eurasia", geo: "Nature", mood: "Relax", tours: "Food"},
        {name: "Saudi Arabia", climate: "Warm", continent: "Eurasia", geo: "City", mood: "Relax", tours: "Food"},
        {name: "Iran", climate: "Warm", continent: "Eurasia", geo: "Nature", mood: "Experience", tours: "Food"},
        {name: "Mongolia", climate: "Cold", continent: "Eurasia", geo: "Nature", mood: "Experience", tours: "Food"},
        {name: "Indonesia", climate: "Warm", continent: "Eurasia", geo: "Nature", mood: "Experience", tours: "Food"},
        {name: "Pakistan", climate: "Warm", continent: "Eurasia", geo: "Nature", mood: "Experience", tours: "Food"},
        {name: "Myanmar", climate: "Warm", continent: "Eurasia", geo: "Nature", mood: "Experience", tours: "Food"},
        {name: "Afghanistan", climate: "Warm", continent: "Eurasia", geo: "Nature", mood: "Experience", tours: "Food"},
        {name: "Yemen", climate: "Warm", continent: "Eurasia", geo: "City", mood: "Experience", tours: "Food"},
        {name: "Thailand", climate: "Warm", continent: "Eurasia", geo: "Nature", mood: "Experience", tours: "Food"},
        {name: "Turkmenistan", climate: "Cold", continent: "Eurasia", geo: "Nature", mood: "Experience", tours: "Food"},
        {name: "Uzbekistan", climate: "Cold", continent: "Eurasia", geo: "Nature", mood: "Experience", tours: "Food"},
        {name: "Iraq", climate: "Warm", continent: "Eurasia", geo: "City", mood: "Experience", tours: "Food"},
        {name: "Japan", climate: "Cold", continent: "Eurasia", geo: "Nature", mood: "Experience", tours: "Food"}
    );
}